# -*- coding: utf-8 -*-
"""Work with sensor data (JSON/CSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx9BKGbettaFk42uoiOBhADHqbcCkLUz
"""

Basic CSV Parsing Code

import csv

# Open CSV file
with open("iot_device_data.csv", "r") as file:
    reader = csv.DictReader(file)

    # Loop through each row
    for row in reader:
        device_id = row["device_id"]
        temperature = float(row["temperature"])
        humidity = float(row["humidity"])
        usage_hours = int(row["usage_hours"])
        error_count = int(row["error_count"])
        vibration = float(row["vibration"])
        device_status = row["device_status"]

        print("Device ID:", device_id)
        print("Temperature:", temperature)
        print("Humidity:", humidity)
        print("Usage Hours:", usage_hours)
        print("Error Count:", error_count)
        print("Vibration:", vibration)
        print("Status:", device_status)
        print("---------------------------")

"""Using numpy and pandas libries with data cleaning and feature Extraction"""