# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yv1lE9M3macxOnn-G27i30Iw-NispzZ6
"""



"""**Data Cleaning and feature Extraction**"""

import pandas as pd
import numpy as np

#Load CSV into DataFrame
df = pd.read_csv("iot_device_data.csv")

print("Original Data:")
print(df.head())

#Data Cleaning

# Replace empty values with NaN
df.replace("", np.nan, inplace=True)

# Fill missing values
df.fillna({
    "temperature": df["temperature"].mean(),
    "humidity": df["humidity"].mean(),
    "usage_hours": 0,
    "error_count": 0,
    "vibration": df["vibration"].median()
}, inplace=True)

# Convert data types
numeric_cols = ["temperature", "humidity", "usage_hours", "error_count", "vibration"]
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Remove duplicates
df.drop_duplicates(inplace=True)

# Handle outliers
df["temperature"] = np.clip(df["temperature"], 20, 80)
df["humidity"] = np.clip(df["humidity"], 30, 100)
df["vibration"] = np.clip(df["vibration"], 0, 2)

# Standardize text
df["device_status"] = df["device_status"].str.lower().str.strip()

df

#Feature Engineering

# 1. Average Temperature per device
df["avg_temp"] = df.groupby("device_id")["temperature"].transform("mean")

# 2. Temperature Change (difference from previous reading)
df["temp_change"] = df.groupby("device_id")["temperature"].diff().fillna(0)

# 3. Usage Frequency (usage per hour approximation)
df["usage_frequency"] = df["usage_hours"] / (df["usage_hours"].max())

# 4. Health Score (reuse + improved)
df["health_score"] = (
    100
    - df["temperature"] * 0.3
    - df["error_count"] * 5
    - df["vibration"] * 10
)

# 5. Health Category
df["health_status"] = np.where(
    df["health_score"] >= 85, "excellent",
    np.where(
        df["health_score"] >= 70, "good",
        np.where(df["health_score"] >= 40, "moderate", "critical")
    )
)

# 6. Risk Flag (ML target feature)
df["is_risky"] = np.where(df["device_status"] == "failure", 1, 0)
df

#Convert Raw → Structured Dataset

# Select important ML-ready features
structured_df = df[[
    "device_id",
    "temperature",
    "humidity",
    "usage_hours",
    "error_count",
    "vibration",
    "avg_temp",
    "temp_change",
    "usage_frequency",
    "health_score",
    "health_status",
    "is_risky"
]]

print("\n Structured Dataset Sample:")
print(structured_df.head())

#Save ML-ready dataset
structured_df.to_csv("ml_ready_iot_data.csv", index=False)

print("\n ML-ready dataset saved as: ml_ready_iot_data.csv")

